package com.example.language_learning.services;

import com.example.language_learning.dto.lessons.*;
import com.example.language_learning.dto.models.ChapterDTO;
import com.example.language_learning.dto.models.ChapterMetadataDTO;
import com.example.language_learning.entity.models.Chapter;
import com.example.language_learning.entity.user.User;
import com.example.language_learning.mapper.DtoMapper;
import com.example.language_learning.repositories.ChapterRepository;
import com.example.language_learning.requests.ChapterGenerationRequest;
import com.example.language_learning.entity.models.LessonBook;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;
import java.util.concurrent.atomic.AtomicInteger;

@Service
@Slf4j
@RequiredArgsConstructor
public class ChapterService {

    private final LessonBookService lessonBookService;
    private final AIService aiService;
    private final VocabularyLessonService vocabularyLessonService;
    private final GrammarLessonService grammarLessonService;
    private final ConjugationLessonService conjugationLessonService;
    private final PracticeLessonService practiceLessonService;
    private final ReadingComprehensionLessonService readingComprehensionLessonService;
    private final ProgressService progressService;
    private final ChapterRepository chapterRepository;
    private final PageService pageService;
    private final DtoMapper dtoMapper;

    /**
     * A public record to act as a clean data carrier for the various DTOs
     * generated by the AI service, avoiding long parameter lists.
     */
    private record GenerationContext(
            VocabularyLessonDTO vocabulary,
            LessonDTO specificLesson
    ){}
    public record BookContext(LessonBook book, int nextChapterNumber, int nextPageNumber) {}

    public ChapterDTO getChapterById(Long chapterId, User user) {
        return chapterRepository.findByIdAndLessonBook_User(chapterId, user)
                .map(dtoMapper::toDto)
                .orElse(null);
    }

    public void generateNewChapterStream(ChapterGenerationRequest request, Long userId, String taskId) {
        getBookContext(request, userId)
                .subscribeOn(Schedulers.boundedElastic()) // Switch to a blocking-safe scheduler for the entire pipeline
                .flatMap(bookContext -> {
                    progressService.sendUpdate(taskId, 10, "Generating chapter outline...");
                    return aiService.generateChapterMetadata(request)
                            .flatMap(metadata -> createInitialChapter(bookContext, metadata))
                            .flatMap(chapter -> generateAndStreamPages(request, taskId, chapter, bookContext.nextPageNumber()));
                })
                .doOnError(error -> {
                    log.error("Chapter generation failed for task {}: {}", taskId, error.getMessage(), error);
                    progressService.sendError(taskId, error);
                })
                .subscribe(
                    null,
                    error -> log.warn("Error propagated to subscribe for task {}. Should be handled by doOnError.", taskId, error),
                        () -> log.info("Chapter generation stream for task {} completed.", taskId)
                );
    }

    private Mono<BookContext> getBookContext(ChapterGenerationRequest request, Long userId) {
        return Mono.fromCallable(() -> {
            LessonBook book = lessonBookService.findOrCreateBook(request.language(), request.difficulty(), userId);
            int nextChapterNumber = book.getChapters().stream()
                    .mapToInt(Chapter::getChapterNumber)
                    .max()
                    .orElse(0) + 1;

            int lastPageNumber = pageService.getLastPageNumberForBook(book.getId());

            return new BookContext(book, nextChapterNumber, lastPageNumber + 1);
        });
    }

    private Mono<Chapter> createInitialChapter(BookContext bookContext, ChapterMetadataDTO metadata) {
        return Mono.fromCallable(() -> {
            Chapter newChapter = Chapter.builder()
                            .lessonBook(bookContext.book())
                            .chapterNumber(bookContext.nextChapterNumber())
                            .title(metadata.title())
                            .nativeTitle(metadata.nativeTitle())
                            .build();
            bookContext.book().addChapter(newChapter);
            return chapterRepository.save(newChapter);
        });
    }

    private Mono<Void> generateAndStreamPages(ChapterGenerationRequest request, String taskId, Chapter chapter, int startingPageNumber) {
        ChapterMetadataDTO metadata = new ChapterMetadataDTO(chapter.getTitle(), chapter.getNativeTitle(), request.topic());
        AtomicInteger pageCounter = new AtomicInteger(startingPageNumber);

        return generateVocabularyLessonPage(request, taskId, chapter, metadata, pageCounter)
                .flatMap(context -> generateGrammarOrConjugationLessonPage(request, taskId, chapter, pageCounter, context))
                .flatMap(context -> generatePracticeLessonPage(request, taskId, chapter, pageCounter, context))
                .flatMap(context -> generateReadingLessonPage(request, taskId, chapter, pageCounter, context))
                .then();
    }

    private Mono<GenerationContext> generateVocabularyLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, ChapterMetadataDTO metadata, AtomicInteger pageCounter) {
        progressService.sendUpdate(taskId, 25, "Creating vocabulary lesson...");
        return vocabularyLessonService.generateLesson(request, metadata)
                .flatMap(lesson -> pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement()))
                .doOnNext(page -> progressService.sendPageUpdate(taskId, 40, "Vocabulary created.", dtoMapper.toDto(page)))
                .map(page -> {
                    VocabularyLessonDTO vocabDto = (VocabularyLessonDTO) dtoMapper.toDto(page.getLesson());
                    return new GenerationContext(vocabDto, null);
                });
    }

    private Mono<GenerationContext> generateGrammarOrConjugationLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, AtomicInteger pageCounter, GenerationContext context) {
        // Generate Grammar Lesson for odd chapters and Conjugation Lesson for even chapters
        if (chapter.getChapterNumber() % 2 != 0) {
            progressService.sendUpdate(taskId, 50, "Explaining grammar rules...");

            return grammarLessonService.generateLesson(request, context.vocabulary())
                    .flatMap(lesson -> pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement()))
                    .doOnNext(page -> progressService.sendPageUpdate(taskId, 60, "Grammar rules explained.", dtoMapper.toDto(page)))
                    .map(page -> new GenerationContext(context.vocabulary(), dtoMapper.toDto(page.getLesson())));
        }
        else {
            progressService.sendUpdate(taskId, 50, "Explaining conjugation rules...");

            return conjugationLessonService.generateLesson(request, context.vocabulary())
                    .flatMap(lesson -> pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement()))
                    .doOnNext(page -> progressService.sendPageUpdate(taskId, 60, "Conjugation rules explained.", dtoMapper.toDto(page)))
                    .map(page -> new GenerationContext(context.vocabulary(), dtoMapper.toDto(page.getLesson())));
        }
    }

    private Mono<GenerationContext> generatePracticeLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, AtomicInteger pageCounter, GenerationContext context) {
        progressService.sendUpdate(taskId, 75, "Building practice exercises...");

        return practiceLessonService.generateLesson(request, context.vocabulary(), context.specificLesson())
                .flatMap(lesson -> pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement()))
                .doOnNext(page -> progressService.sendPageUpdate(taskId, 85, "Practice exercises built.", dtoMapper.toDto(page)))
                .thenReturn(context);
    }

    private Mono<GenerationContext> generateReadingLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, AtomicInteger pageCounter, GenerationContext context) {
        progressService.sendUpdate(taskId, 90, "Writing reading passage...");

        return readingComprehensionLessonService.generateLesson(request, context.vocabulary(), context.specificLesson())
                .flatMap(lesson -> pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement()))
                .doOnNext(page -> progressService.sendPageUpdate(taskId, 100, "Chapter generation complete.", dtoMapper.toDto(page)))
                .thenReturn(context);
    }

}
