package com.example.language_learning.services;

import com.example.language_learning.dto.lessons.*;
import com.example.language_learning.dto.models.ChapterMetadataDTO;
import com.example.language_learning.requests.ChapterGenerationRequest;
import com.example.language_learning.dto.models.ChapterDTO;
import com.example.language_learning.entity.models.LessonBook;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

@Service
@Slf4j
@RequiredArgsConstructor
public class ChapterService {

    private final BookService bookService;
    private final AIService aiService;
    private final VocabularyLessonService vocabularyLessonService;
    private final GrammarLessonService grammarLessonService;
    private final ConjugationLessonService conjugationLessonService;
    private final PracticeLessonService practiceLessonService;
    private final ReadingComprehensionLessonService readingComprehensionLessonService;
    private final ProgressService progressService;
    private final ChapterPersistenceService chapterPersistenceService;
    /**
     * A public record to act as a clean data carrier for the various DTOs
     * generated by the AI service, avoiding long parameter lists.
     */
    public record GeneratedComponents(
            ChapterMetadataDTO metadata,
            VocabularyLessonDTO vocabulary,
            GrammarLessonDTO grammar,
            ConjugationLessonDTO conjugation,
            PracticeLessonDTO practice,
            ReadingComprehensionLessonDTO reading) { }
    public record BookContext(LessonBook book, int nextChapterNumber) {}

    public void generateNewChapterStream(ChapterGenerationRequest request, String taskId) {
        // A record to pass context through the reactive chain

        getBookContext(request)
                .publishOn(Schedulers.boundedElastic()) // Switch to a blocking-safe scheduler for the entire pipeline
                .flatMap(bookContext -> generateAndSaveChapter(request, taskId, bookContext))
                .subscribe(
                        newChapter -> progressService.sendComplete(taskId, newChapter),
                        error -> handleGenerationError(taskId, error)
                );
    }

    private Mono<ChapterService.BookContext> getBookContext(ChapterGenerationRequest request) {
        return Mono.fromCallable(() -> {
            LessonBook book = bookService.findOrCreateBook(request.language(), request.difficulty(), request.userId());
            int nextChapterNumber = book.getChapters().stream()
                    .mapToInt(com.example.language_learning.entity.models.Chapter::getChapterNumber)
                    .max()
                    .orElse(0) + 1;
            return new BookContext(book, nextChapterNumber);
        });
    }

    private Mono<ChapterDTO> generateAndSaveChapter(ChapterGenerationRequest request, String taskId, BookContext bookContext) {
        progressService.sendUpdate(taskId, 10, "Generating chapter outline...");

        return generateChapterComponents(request, taskId, bookContext)
                .flatMap(components -> Mono.fromCallable(() ->
                        chapterPersistenceService.saveChapterComponents(bookContext.book(), bookContext.nextChapterNumber(), components)
                ));
    }

    private Mono<GeneratedComponents> generateChapterComponents(ChapterGenerationRequest request, String taskId, BookContext bookContext) {
        return aiService.generateChapterMetadata(request)
                .doOnSuccess(metadata -> progressService.sendUpdate(taskId, 25, "Creating vocabulary lesson..."))
                .flatMap(metadata -> aiService.generateVocabularyLesson(request, metadata)
                        .flatMap(vocabulary -> generateLessonPath(request, taskId, bookContext, metadata, vocabulary))
                );
    }

    private Mono<GeneratedComponents> generateLessonPath(ChapterGenerationRequest request, String taskId, BookContext bookContext,
                                                         ChapterMetadataDTO metadata, VocabularyLessonDTO vocabulary) {
        if (bookContext.nextChapterNumber() % 2 != 0) {
            progressService.sendUpdate(taskId, 50, "Explaining grammar rules...");
            return aiService.generateGrammarLesson(request, vocabulary)
                    .doOnSuccess(g -> progressService.sendUpdate(taskId, 75, "Building practice exercises..."))
                    .flatMap(grammar -> aiService.generatePracticeLesson(request, vocabulary, grammar)
                            .doOnSuccess(p -> progressService.sendUpdate(taskId, 90, "Writing reading passage..."))
                            .flatMap(practice -> aiService.generateReadingComprehensionLesson(request, vocabulary, grammar)
                                    .map(reading -> new GeneratedComponents(metadata, vocabulary, grammar, null, practice, reading))
                            )
                    );
        } else {
            progressService.sendUpdate(taskId, 50, "Explaining conjugation rules...");
            return aiService.generateConjugationLesson(request, vocabulary)
                    .doOnSuccess(c -> progressService.sendUpdate(taskId, 75, "Building practice exercises..."))
                    .flatMap(conjugation -> aiService.generatePracticeLesson(request, vocabulary, conjugation)
                            .doOnSuccess(p -> progressService.sendUpdate(taskId, 90, "Writing reading passage..."))
                            .flatMap(practice -> aiService.generateReadingComprehensionLesson(request, vocabulary, conjugation)
                                    .map(reading -> new GeneratedComponents(metadata, vocabulary, null, conjugation, practice, reading))
                            )
                    );
        }
    }

    private void handleGenerationError(String taskId, Throwable error) {
        log.error("Error during chapter generation for task {}: {}", taskId, error.getMessage(), error);
        progressService.sendError(taskId, "Chapter generation failed: " + error.getMessage());
    }
}
