package com.example.language_learning.services;

import com.example.language_learning.dto.lessons.*;
import com.example.language_learning.dto.models.ChapterMetadataDTO;
import com.example.language_learning.entity.models.Chapter;
import com.example.language_learning.entity.user.User;
import com.example.language_learning.mapper.DtoMapper;
import com.example.language_learning.requests.ChapterGenerationRequest;
import com.example.language_learning.entity.models.LessonBook;
import com.example.language_learning.responses.GenerationResponse;
import lombok.Builder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

@Service
@Slf4j
@RequiredArgsConstructor
public class ChapterGenerationService {

    private final LessonBookService lessonBookService;
    private final AIService aiService;
    private final VocabularyLessonService vocabularyLessonService;
    private final GrammarLessonService grammarLessonService;
    private final ConjugationLessonService conjugationLessonService;
    private final PracticeLessonService practiceLessonService;
    private final ReadingComprehensionLessonService readingComprehensionLessonService;
    private final ProgressService progressService;
    private final ChapterService chapterService;
    private final PageService pageService;
    private final DtoMapper dtoMapper;

    /**
     * A public record to act as a clean data carrier for the various DTOs
     * generated by the AI service, avoiding long parameter lists.
     */
    private record GenerationContext(
            VocabularyLessonDTO vocabulary,
            LessonDTO specificLesson
    ){}

    @Builder
    private record ChapterPreparation(String taskId, Chapter chapter, int startingPageNumber) {}

    @Transactional
    public GenerationResponse generateChapter(ChapterGenerationRequest request, User user) {
        // 1. We retrieve the initial Chapter with metadata required for the initial request
        ChapterPreparation prep = prepareChapterGeneration(request, user);

        // 2. Kick off the chapter generation pipeline to create the associated lesson pages asynchronously
        //    after the current transaction successfully commit.s
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
            @Override
            public void afterCommit() {
                generateChapterAsync(request, prep.taskId(), prep.chapter().getId(), prep.startingPageNumber());
            }
        });

        // 3. Return the expected generation response
        return GenerationResponse.builder()
                .taskId(prep.taskId())
                .chapter(dtoMapper.toDto(prep.chapter()))
                .build();
    }

    private ChapterPreparation prepareChapterGeneration(ChapterGenerationRequest request, User user) {
        final String taskId = UUID.randomUUID().toString();

        // 1. Find or create the lesson book.
        LessonBook book = lessonBookService.findOrCreateBook(request.language(), request.difficulty(), user);

        // 2. Generate chapter metadata from the AI service.
        ChapterMetadataDTO metadata = aiService.generateChapterMetadata(request).block();
        if (metadata == null) {
            throw new IllegalStateException("Failed to generate chapter metadata from AI service.");
        }

        // 3. Determine the next chapter number.
        int nextChapterNumber = book.getChapters().stream()
                .mapToInt(Chapter::getChapterNumber)
                .max()
                .orElse(0) + 1;

        // 4. Create the chapter shell for the new chapter
        Chapter newChapter = chapterService.createChapter(book, nextChapterNumber, metadata.title(), metadata.nativeTitle());

        // 5. Calculate the starting page number for the new chapter.
        int lastPageNumber = pageService.getLastPageNumberForBook(book.getId());
        int nextPageNumber = lastPageNumber + 1;

        // 6. Return the Chapter Generation Response & the page(s) generation pipeline will kick in
        return ChapterPreparation.builder()
                .taskId(taskId)
                .chapter(newChapter)
                .startingPageNumber(nextPageNumber)
                .build();
    }

    private void generateChapterAsync(ChapterGenerationRequest request, String taskId, Long chapterId, int startingPageNumber) {
        // Asynchronously start the page(s) generation for the chapter generation subscription
        Mono.fromRunnable(() -> progressService.sendUpdate(taskId, 10, "Generating chapter outline..."))
             .then(Mono.fromCallable(() -> chapterService.getChapter(chapterId)
                        .orElseThrow(() -> new RuntimeException("Chapter not found for async generation: " + chapterId))
             ))
            .flatMap(chapter -> generateAndStreamPages(request, taskId, chapter, startingPageNumber))
            .doOnError(error -> {
                log.error("Chapter generation failed for task {}: {}", taskId, error.getMessage(), error);
                progressService.sendError(taskId, error);
            })
            .doFinally(signalType -> log.info("Chapter generation stream for task {} finished with signal: {}", taskId, signalType))
            .subscribeOn(Schedulers.boundedElastic())
            .subscribe();
    }

    private Mono<Void> generateAndStreamPages(ChapterGenerationRequest request, String taskId, Chapter chapter, int startingPageNumber) {
        ChapterMetadataDTO metadata = new ChapterMetadataDTO(chapter.getTitle(), chapter.getNativeTitle(), request.topic());
        AtomicInteger pageCounter = new AtomicInteger(startingPageNumber);

        return generateVocabularyLessonPage(request, taskId, chapter, metadata, pageCounter)
                .flatMap(context -> generateGrammarOrConjugationLessonPage(request, taskId, chapter, pageCounter, context))
                .flatMap(context -> generatePracticeLessonPage(request, taskId, chapter, pageCounter, context))
                .flatMap(context -> generateReadingLessonPage(request, taskId, chapter, pageCounter, context))
                .then();
    }

    private Mono<GenerationContext> generateVocabularyLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, ChapterMetadataDTO metadata, AtomicInteger pageCounter) {
        return Mono.fromRunnable(() -> progressService.sendUpdate(taskId, 25, "Creating vocabulary lesson..."))
                //.subscribeOn(Schedulers.boundedElastic())
                .then(Mono.defer(() -> vocabularyLessonService.generateLesson(request, metadata)))
                .flatMap(lesson -> Mono.fromCallable(() ->
                    pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement())
                ))
                .doOnNext(page -> progressService.sendPageUpdate(taskId, 40, "Vocabulary created.", chapter.getId(), dtoMapper.toDto(page)))
                .map(page -> {
                    VocabularyLessonDTO vocabDto = (VocabularyLessonDTO) dtoMapper.toDto(page.getLesson());
                    return new GenerationContext(vocabDto, null);
                });
    }

    private Mono<GenerationContext> generateGrammarOrConjugationLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, AtomicInteger pageCounter, GenerationContext context) {
        // Generate Grammar Lesson for odd chapters and Conjugation Lesson for even chapters
        if (chapter.getChapterNumber() % 2 != 0) {
            return Mono.fromRunnable(() ->  progressService.sendUpdate(taskId, 50, "Explaining grammar rules..."))
                    //.subscribeOn(Schedulers.boundedElastic())
                    .then(Mono.defer(() -> grammarLessonService.generateLesson(request, context.vocabulary())))
                    .flatMap(lesson -> Mono.fromCallable(() ->
                        pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement())
                    ))
                    .doOnNext(page -> progressService.sendPageUpdate(taskId, 60, "Grammar rules explained.", chapter.getId(), dtoMapper.toDto(page)))
                    .map(page -> new GenerationContext(context.vocabulary(), dtoMapper.toDto(page.getLesson())));
        }
        else {
            return Mono.fromRunnable(() -> progressService.sendUpdate(taskId, 50, "Explaining conjugation rules..."))
                    //.subscribeOn(Schedulers.boundedElastic())
                    .then(Mono.defer(() -> conjugationLessonService.generateLesson(request, context.vocabulary())))
                    .flatMap(lesson -> Mono.fromCallable(() ->
                        pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement())
                    ))
                    .doOnNext(page -> progressService.sendPageUpdate(taskId, 60, "Conjugation rules explained.", chapter.getId(), dtoMapper.toDto(page)))
                    .map(page -> new GenerationContext(context.vocabulary(), dtoMapper.toDto(page.getLesson())));
        }
    }

    private Mono<GenerationContext> generatePracticeLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, AtomicInteger pageCounter, GenerationContext context) {
        return Mono.fromRunnable(() -> progressService.sendUpdate(taskId, 75, "Building practice exercises..."))
                //.subscribeOn(Schedulers.boundedElastic())
                .then(Mono.defer(() -> practiceLessonService.generateLesson(request, context.vocabulary(), context.specificLesson())))
                .flatMap(lesson -> Mono.fromCallable(() ->
                    pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement())
                ))
                .doOnNext(page -> progressService.sendPageUpdate(taskId, 85, "Practice exercises built.", chapter.getId(), dtoMapper.toDto(page)))
                .thenReturn(context);
    }

    private Mono<GenerationContext> generateReadingLessonPage(ChapterGenerationRequest request, String taskId, Chapter chapter, AtomicInteger pageCounter, GenerationContext context) {
        return Mono.fromRunnable(() -> progressService.sendUpdate(taskId, 90, "Writing reading passage..."))
                //.subscribeOn(Schedulers.boundedElastic())
                .then(Mono.defer(() -> readingComprehensionLessonService.generateLesson(request, context.vocabulary(), context.specificLesson())))
                .flatMap(lesson -> Mono.fromCallable(() ->
                    pageService.createAndPersistPage(chapter, lesson, pageCounter.getAndIncrement())
                ))
                .doOnNext(page -> progressService.sendPageUpdate(taskId, 100, "Chapter generation complete.", chapter.getId(), dtoMapper.toDto(page)))
                .thenReturn(context);
    }

}
