package com.example.language_learning.services;

import com.example.language_learning.dto.lessons.*;
import com.example.language_learning.dto.models.ChapterDTO;
import com.example.language_learning.dto.models.ChapterMetadataDTO;
import com.example.language_learning.requests.ChapterGenerationRequest;
import com.example.language_learning.entity.models.LessonBook;
import com.example.language_learning.entity.models.Chapter;
import com.example.language_learning.entity.models.Page;
import com.example.language_learning.mapper.DtoMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import reactor.core.publisher.Mono;

@Service
@RequiredArgsConstructor
public class ChapterService {

    private final BookService bookService;
    private final AIService aiService;
    private final VocabularyLessonService vocabularyLessonService;
    private final GrammarLessonService grammarLessonService;
    private final ConjugationLessonService conjugationLessonService;
    private final PracticeLessonService practiceLessonService;
    private final ReadingComprehensionLessonService readingComprehensionLessonService;
    private final DtoMapper mapper;

    /**
     * A private record to act as a clean data carrier for the various DTOs
     * generated by the AI service, avoiding long parameter lists.
     */
    private record ChapterComponents(
            ChapterMetadataDTO metadata,
            VocabularyLessonDTO vocabulary,
            GrammarLessonDTO grammar,
            ConjugationLessonDTO conjugation,
            PracticeLessonDTO practice,
            ReadingComprehensionLessonDTO reading) {}

    @Transactional
    public ChapterDTO generateNewChapter(ChapterGenerationRequest request) {
        // 1. Find an existing or create the lesson book
        LessonBook book = bookService.findOrCreateBook(request.language(), request.difficulty(), request.userId());
        int nextChapterNumber = book.getChapters().stream()
                .mapToInt(Chapter::getChapterNumber)
                .max()
                .orElse(0) + 1;

        // 2. Sequentially generate all lesson components using a reactive pipeline.
        ChapterComponents components = aiService.generateChapterMetadata(request)
                .flatMap(metadata -> aiService.generateVocabularyLesson(request, metadata)
                        .flatMap(vocabulary -> {
                            if (nextChapterNumber % 2 != 0) {
                                return aiService.generateGrammarLesson(request, vocabulary)
                                        .flatMap(grammar -> aiService.generatePracticeLesson(request, vocabulary, grammar)
                                                .flatMap(practice -> aiService.generateReadingComprehensionLesson(request, vocabulary, grammar)
                                                        .map(reading -> new ChapterComponents(metadata, vocabulary, grammar, null, practice, reading))
                                                )
                                        );
                            }
                            else {
                                return aiService.generateConjugationLesson(request, vocabulary)
                                        .flatMap(conjugation -> aiService.generatePracticeLesson(request, vocabulary, conjugation)
                                                .flatMap(practice -> aiService.generateReadingComprehensionLesson(request, vocabulary, conjugation)
                                                        .map(reading -> new ChapterComponents(metadata, vocabulary, null, conjugation, practice, reading))
                                                )
                                        );
                            }
                        })
                ).block();

        if (components == null) {
            throw new IllegalStateException("Failed to generate all required chapter components.");
        }

        // 3. Assemble and save the chapter within the transaction
        Chapter chapter = createChapter(book, nextChapterNumber, components);
        book.addChapter(chapter);
        LessonBook savedBook = bookService.save(book);

        return savedBook.getChapters().stream()
                .filter(c -> c.getChapterNumber() == nextChapterNumber)
                .findFirst()
                .map(mapper::toDto)
                .orElseThrow(() -> new IllegalStateException("Failed to find newly saved chapter"));
    }

    private Chapter createChapter(LessonBook book, int chapterNumber, ChapterComponents components) {
        Chapter chapter = new Chapter();
        chapter.setTitle(components.metadata().title());
        chapter.setNativeTitle(components.metadata().nativeTitle());
        chapter.setChapterNumber(chapterNumber);

        int lastPageNumber = book.getChapters().stream()
                .flatMap(c -> c.getPages().stream())
                .mapToInt(Page::getPageNumber)
                .max()
                .orElse(0);

        chapter.addPage(new Page(lastPageNumber + 1, vocabularyLessonService.createVocabularyLesson(components.vocabulary())));
        if (components.grammar() != null) {
            chapter.addPage(new Page(lastPageNumber + 2, grammarLessonService.createGrammarLesson(components.grammar())));
        } else if (components.conjugation() != null) {
            chapter.addPage(new Page(lastPageNumber + 2, conjugationLessonService.createConjugationLesson(components.conjugation())));
        }
        chapter.addPage(new Page(lastPageNumber + 3, practiceLessonService.createPracticeLesson(components.practice())));
        chapter.addPage(new Page(lastPageNumber + 4, readingComprehensionLessonService.createReadingComprehensionLesson(components.reading())));

        return chapter;
    }

}
