create table if not exists conjugation_examples (created_at timestamp(6) not null default now(), id bigint generated by default as identity, conjugated_form TEXT, example_sentence TEXT, infinitive varchar(255), sentence_translation TEXT, primary key (id));
create table if not exists conjugation_lesson_examples (lesson_id bigint not null, example_id bigint not null unique);
create table if not exists conjugation_lessons (id bigint not null, conjugation_rule_name varchar(255), explanation TEXT, primary key (id));
create table if not exists grammar_lesson_sentences (lesson_id bigint not null, sentence_id bigint not null unique);
create table if not exists grammar_lessons (id bigint not null, explanation TEXT, grammar_concept TEXT, primary key (id));
create table if not exists lesson_books (created_at timestamp(6) not null default now(), id bigint generated by default as identity, user_id bigint, difficulty varchar(255), language varchar(255), title varchar(255), primary key (id));
create table if not exists lesson_chapters (created_at timestamp(6) not null default now(), book_id bigint, id bigint generated by default as identity, native_title varchar(255) not null, title varchar(255) not null, primary key (id));
create table if not exists lesson_pages (created_at timestamp(6) not null default now(), id bigint generated by default as identity, lesson_chapter_id bigint, lesson_id bigint unique, primary key (id));
create table if not exists lesson_questions (created_at timestamp(6) not null default now(), id bigint generated by default as identity, lesson_id bigint not null, answer TEXT, question_text TEXT, question_type varchar(255) check (question_type in ('MULTIPLE_CHOICE','FREE_FORM')), primary key (id));
create table if not exists lessons (created_at timestamp(6) not null default now(), id bigint generated by default as identity, title varchar(255), type varchar(255) check (type in ('VOCABULARY','GRAMMAR','CONJUGATION','PRACTICE','READING_COMPREHENSION')), primary key (id));
create table if not exists practice_lessons (id bigint not null, instructions TEXT, primary key (id));
create table if not exists question_answer_choices (question_id bigint not null, answer_choice TEXT);
create table if not exists reading_comprehension_lessons (id bigint not null, story TEXT, primary key (id));
create table if not exists sentences (created_at timestamp(6) not null default now(), id bigint generated by default as identity, text TEXT, translation TEXT, primary key (id));
create table if not exists settings (auto_speak_enabled boolean default true not null, created_at timestamp(6) not null default now(), id bigint generated by default as identity, difficulty varchar(255), language varchar(255), mascot varchar(255) not null, theme varchar(255) not null, primary key (id));
create table if not exists short_stories (created_at timestamp(6) not null default now(), id bigint generated by default as identity, story_book_id bigint, genre varchar(255), native_title varchar(255) not null, title varchar(255) not null, topic varchar(255), primary key (id));
create table if not exists story_books (created_at timestamp(6) not null default now(), id bigint generated by default as identity, user_id bigint, difficulty varchar(255), language varchar(255), title varchar(255), primary key (id));
create table if not exists story_pages (created_at timestamp(6) not null default now(), id bigint generated by default as identity, short_story_id bigint, english_summary TEXT, image_url TEXT, type varchar(255) check (type in ('CONTENT','VOCABULARY')), primary key (id));
create table if not exists story_paragraphs (paragraph_number integer not null, created_at timestamp(6) not null default now(), id bigint generated by default as identity, story_page_id bigint, content TEXT, words_to_highlight jsonb not null default '[]'::jsonb, primary key (id));
create table if not exists story_vocabulary_items (created_at timestamp(6) not null default now(), id bigint generated by default as identity, story_page_id bigint, translation varchar(255), word varchar(255) not null, stem varchar(255) not null, primary key (id));
create table if not exists users (created_at timestamp(6) not null default now(), id bigint generated by default as identity, settings_id bigint unique, password varchar(255) not null, username varchar(255) not null unique, email varchar(255) not null unique, refresh_token TEXT, refresh_token_expiry timestamptz(6), primary key (id));
create table if not exists vocabulary_lesson_words (lesson_id bigint not null, word_id bigint not null);
create table if not exists vocabulary_lessons (id bigint not null, primary key (id));
create table if not exists words (created_at timestamp(6) not null default now(), id bigint generated by default as identity, english_translation TEXT not null, language varchar(255) not null, details jsonb, primary key (id));

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_conjugation_lesson_examples_example') THEN
        ALTER TABLE conjugation_lesson_examples ADD CONSTRAINT FK_conjugation_lesson_examples_example FOREIGN KEY (example_id) REFERENCES conjugation_examples;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_conjugation_lesson_examples_lesson') THEN
        ALTER TABLE conjugation_lesson_examples ADD CONSTRAINT FK_conjugation_lesson_examples_lesson FOREIGN KEY (lesson_id) REFERENCES conjugation_lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk38tvralx9sggqagut8t4sdcj3') THEN
        ALTER TABLE conjugation_lessons ADD CONSTRAINT FK38tvralx9sggqagut8t4sdcj3 FOREIGN KEY (id) REFERENCES lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkp5swjw3r4thggv392p9utulqm') THEN
        ALTER TABLE grammar_lesson_sentences ADD CONSTRAINT FKp5swjw3r4thggv392p9utulqm FOREIGN KEY (sentence_id) REFERENCES sentences;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkfkj12tr05q4scrym82ghb4kqc') THEN
        ALTER TABLE grammar_lesson_sentences ADD CONSTRAINT FKfkj12tr05q4scrym82ghb4kqc FOREIGN KEY (lesson_id) REFERENCES grammar_lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkiku87of20ehy5nat5k3eyxr0b') THEN
        ALTER TABLE grammar_lessons ADD CONSTRAINT FKiku87of20ehy5nat5k3eyxr0b FOREIGN KEY (id) REFERENCES lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkaq34h556my3xj1uyhmcdh5p9g') THEN
        ALTER TABLE lesson_books ADD CONSTRAINT FKaq34h556my3xj1uyhmcdh5p9g FOREIGN KEY (user_id) REFERENCES users;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk4n8mf34ts1tw2pmxcgq95gc98') THEN
        ALTER TABLE lesson_chapters ADD CONSTRAINT FK4n8mf34ts1tw2pmxcgq95gc98 FOREIGN KEY (book_id) REFERENCES lesson_books;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkf34yriwekstcr137vbct6bk6l') THEN
        ALTER TABLE lesson_pages ADD CONSTRAINT FKf34yriwekstcr137vbct6bk6l FOREIGN KEY (lesson_id) REFERENCES lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk121yhtjjax5kdf2o0llruvvci') THEN
        ALTER TABLE lesson_pages ADD CONSTRAINT FK121yhtjjax5kdf2o0llruvvci FOREIGN KEY (lesson_chapter_id) REFERENCES lesson_chapters;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkl0a4v5xv61hj4kr7664r07ut0') THEN
        ALTER TABLE lesson_questions ADD CONSTRAINT FKl0a4v5xv61hj4kr7664r07ut0 FOREIGN KEY (lesson_id) REFERENCES lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk8iq3tjr4iqdr0v789y775pdo7') THEN
        ALTER TABLE practice_lessons ADD CONSTRAINT FK8iq3tjr4iqdr0v789y775pdo7 FOREIGN KEY (id) REFERENCES lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkr4beqxc7ll2onu0k2kux71fq2') THEN
        ALTER TABLE question_answer_choices ADD CONSTRAINT FKr4beqxc7ll2onu0k2kux71fq2 FOREIGN KEY (question_id) REFERENCES lesson_questions;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk9g4g29tnwvrlrtis6x20ixbfo') THEN
        ALTER TABLE reading_comprehension_lessons ADD CONSTRAINT FK9g4g29tnwvrlrtis6x20ixbfo FOREIGN KEY (id) REFERENCES lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk3g024dhd3tkmhfobm4x3s9pgx') THEN
        ALTER TABLE short_stories ADD CONSTRAINT FK3g024dhd3tkmhfobm4x3s9pgx FOREIGN KEY (story_book_id) REFERENCES story_books;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk8ce8x1mkoah3kvh1hnt9ofa84') THEN
        ALTER TABLE story_books ADD CONSTRAINT FK8ce8x1mkoah3kvh1hnt9ofa84 FOREIGN KEY (user_id) REFERENCES users;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk7u0vihcdi1qa4ncdii74i2tg5') THEN
        ALTER TABLE story_pages ADD CONSTRAINT FK7u0vihcdi1qa4ncdii74i2tg5 FOREIGN KEY (short_story_id) REFERENCES short_stories;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkmivhc3exlmc0k69rq23uvqtgt') THEN
        ALTER TABLE story_paragraphs ADD CONSTRAINT FKmivhc3exlmc0k69rq23uvqtgt FOREIGN KEY (story_page_id) REFERENCES story_pages;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkog8a7akffx0hg151p6nfwgaa9') THEN
        ALTER TABLE story_vocabulary_items ADD CONSTRAINT FKog8a7akffx0hg151p6nfwgaa9 FOREIGN KEY (story_page_id) REFERENCES story_pages;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkkq8mvg6xlyeewn7xnf0usloiq') THEN
        ALTER TABLE users ADD CONSTRAINT FKkq8mvg6xlyeewn7xnf0usloiq FOREIGN KEY (settings_id) REFERENCES settings;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fktom5gmk7j9j2twl2jgj3y5vgs') THEN
        ALTER TABLE vocabulary_lesson_words ADD CONSTRAINT FKtom5gmk7j9j2twl2jgj3y5vgs FOREIGN KEY (word_id) REFERENCES words;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk8wyxitqffta5mdc13m24kg97f') THEN
        ALTER TABLE vocabulary_lesson_words ADD CONSTRAINT FK8wyxitqffta5mdc13m24kg97f FOREIGN KEY (lesson_id) REFERENCES vocabulary_lessons;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkhph8a887h0miud0nxrlne4n6b') THEN
        ALTER TABLE vocabulary_lessons ADD CONSTRAINT FKhph8a887h0miud0nxrlne4n6b FOREIGN KEY (id) REFERENCES lessons;
    END IF;
END;
$$;
