package com.example.language_learning.ai.outputs;

import com.example.language_learning.lessonbook.chapter.data.Chapter;
import com.example.language_learning.lessonbook.data.LessonBook;
import lombok.Data;

/**
 * A mutable class to hold all outputs generated by the chapter preparation workflow tasks.
 */
@Data
public class ChapterPrepOutput {
    private String taskId;
    private LessonBook book;
    private Chapter chapter;
    private int startingPageNumber;
}