package com.example.language_learning.ai.outputs;

import com.example.language_learning.lessonbook.chapter.LessonChapter;
import com.example.language_learning.lessonbook.LessonBook;
import lombok.Data;

/**
 * A mutable class to hold all outputs generated by the lessonChapter preparation workflow tasks.
 */
@Data
public class ChapterPrepOutput {
    private String taskId;
    private LessonBook book;
    private LessonChapter lessonChapter;
}