spring.application.name=language-learning
# This tells Spring/Hibernate which SQL dialect to use for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# This tells Hibernate to update the database schema on startup based on your entities.
# Use "validate" in production.
spring.jpa.hibernate.ddl-auto=update
