spring.application.name=language-learning
management.endpoints.web.exposure.include=health
spring.mvc.async.request-timeout=90000
# Use "validate" in production.
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

#Postgres
spring.datasource.url=jdbc:postgresql://postgres:5433/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
