spring:
  application:
    name: language-learning
  jpa:
    hibernate:
      #ddl-auto: create-drop # Use "validate" in production to avoid accidental data loss.
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    async:
      request-timeout: 90000
  ai:
    # Disable auto-configuration to allow for full manual bean definition.
    model:
      chat: none
      embedding: none
    ollama1:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL}
      chat:
        options:
          format: json
          num-ctx: 8192
          num-predict: 8192
          temperature: 0.5

    ollama2:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL}
      chat:
        options:
          format: json
          num-ctx: 8192
          num-predict: 8192
          temperature: 0.5

    ollama3:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL}
      chat:
        options:
          format: json
          num-ctx: 8192
          num-predict: 8192
          temperature: 0.5

logging:
  level:
    org.springframework.security: WARN
    org.springframework.boot.actuate.health: WARN

management:
  endpoints:
    web:
      exposure:
        include: health

application:
  security:
    jwt:
      secret-key: "pdbhjA+O1PBFGHMIpW9KYnA1cNsNePgh4zaCn5EpMkA="
      expiration: 86400000